apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "doen.fullname" . }}
  labels: {{- include "doen.labels" . | nindent 4 }}
data:
  DB_MODE: {{ .Values.config.dbMode | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
  HA_BASE_URL: {{ .Values.config.haBaseUrl | quote }}
  HA_CLIENT_ID: {{ .Values.config.haClientId | quote }}
