apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "doen.fullname" . }}
  labels: {{- include "doen.labels" . | nindent 4 }}
  annotations:
    keel.sh/policy: {{ .Values.keel.policy | quote }}
    keel.sh/trigger: poll
    keel.sh/pollSchedule: {{ .Values.keel.pollSchedule | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "doen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "doen.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: doen
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "doen.fullname" . }}
            - secretRef:
                name: {{ include "doen.fullname" . }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "doen.fullname" . }}
      {{- end }}
